---
molecule:
  ignore_paths:
    - venv
lint:
  name: yamllint .
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04.4
    pre_build_image: true
provisioner:
  name: ansible
  log: true
lint: |
  set -e
  ansible-lint --force-color
verifier:
  name: ansible
